version: '3.8'

# Complete Observability Stack for Orchestrall Platform
# Provides comprehensive tracing, logging, and monitoring capabilities

services:
  # ========================================
  # Distributed Tracing (OpenTelemetry + Jaeger)
  # ========================================
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: orchestrall-jaeger
    ports:
      - "16686:16686"        # Jaeger UI
      - "14268:14268"        # Accept traces from OpenTelemetry
      - "14250:14250"        # Accept traces from Jaeger clients
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - SPAN_STORAGE_TYPE=badger
      - BADGER_EPHEMERAL=false
      - BADGER_DIRECTORY_VALUE=/badger/data
      - BADGER_DIRECTORY_KEY=/badger/key
    volumes:
      - jaeger_data:/badger
    restart: unless-stopped
    networks:
      - observability

  # ========================================
  # Metrics Collection (Prometheus)
  # ========================================
  prometheus:
    image: prom/prometheus:latest
    container_name: orchestrall-prometheus
    ports:
      - "9090:9090"          # Prometheus UI and API
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - observability

  # ========================================
  # Log Aggregation (Loki)
  # ========================================
  loki:
    image: grafana/loki:latest
    container_name: orchestrall-loki
    ports:
      - "3100:3100"          # Loki API
    volumes:
      - ./observability/loki-config.yml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - observability

  # ========================================
  # Log Collection (Promtail)
  # ========================================
  promtail:
    image: grafana/promtail:latest
    container_name: orchestrall-promtail
    volumes:
      - ./logs:/var/log/orchestrall:ro
      - ./observability/promtail-config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - observability

  # ========================================
  # Monitoring Dashboard (Grafana)
  # ========================================
  grafana:
    image: grafana/grafana:latest
    container_name: orchestrall-grafana
    ports:
      - "3000:3000"          # Grafana UI
    volumes:
      - grafana_data:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-loki-datasource,grafana-jaeger-datasource
    restart: unless-stopped
    networks:
      - observability
    depends_on:
      - loki
      - jaeger
      - prometheus

  # ========================================
  # Optional: Alert Manager (for advanced alerting)
  # ========================================
  alertmanager:
    image: prom/alertmanager:latest
    container_name: orchestrall-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./observability/alertmanager.yml:/etc/alertmanager/config.yml:ro
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    networks:
      - observability

volumes:
  jaeger_data:
    driver: local
  prometheus_data:
    driver: local
  loki_data:
    driver: local
  grafana_data:
    driver: local
  alertmanager_data:
    driver: local

networks:
  observability:
    driver: bridge
