# Prometheus Configuration for Orchestrall Platform

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Application metrics from OpenTelemetry
  - job_name: 'orchestrall-services'
    static_configs:
      - targets: ['host.docker.internal:9464']  # Application metrics port
    scrape_interval: 10s
    metrics_path: '/metrics'

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Grafana metrics (if enabled)
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # Jaeger metrics (if available)
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 30s
