[phases.setup]
nixPkgs = ["nodejs", "npm", "postgresql"]

[phases.install]
cmds = [
  "npm ci --only=production",
  "npx prisma generate",
  "npx prisma migrate deploy"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm run start:production"
